apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "kong.fullname" . }}"
  labels:
{{- include "kong.metaLabels" . | nindent 4 }}
  app.kubernetes.io/component: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ template "kong.fullname" . }}"
  minReplicas: {{ .Values.global.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.global.autoscaling.metrics | nindent 4 }}
