dependencies:
- name: postgresql
  version: ~8.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: kong-hpa
  alias: kong
  version: 1.2.0
  condition: global.autoscaling.enabled

